version: "1.0"
services:
  mongodb:
    image: mongo
    container_name: mongodb123
    volumes:
      - mongo_data:/data/db

  server:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    container_name: server
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URL=mongodb://mongodb123:27017/chatapp
      - SECRET_KEY
      - SERVER_PORT=8080
      - APP_BASE_URL=http://localhost:5173/

  app:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    container_name: application
    volumes:
      - /frontend/src
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - server
    environment:
      - WATCHPACK_POLLING=true
volumes:
  mongo_data:
