version: "1.0"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb123
    volumes:
      - mongo_data:/data/db

  server:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    container_name: server
    depends_on:
      - mongodb
    ports:
      - "8080:8080"

  app:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    container_name: application
    volumes:
      - /data/src
    ports:
      - "80:80"
    depends_on:
      - mongodb
      - server

volumes:
  mongo_data:
