# version: "1.0"
# services:
#   mongodb:
#     image: mongo
#     container_name: mongodb123
#     volumes:
#       - mongo_data:/data/db

#   server:
#     image: vijaybantu24/chatapp_backend:test
#     container_name: server
#     depends_on:
#       - mongodb
#     ports:
#       - "8080:8080"
#     environment:
#       - MONGODB_URL=mongodb://mongodb123:27017/chatapp
#       - SECRET_KEY
#       - SERVER_PORT=8080
#       - APP_BASE_URL=http://localhost:5173/

#   app:
#     build: ./
#     container_name: application
#     volumes:
#       - /frontend/src
#     ports:
#       - "5173:5173"
#     depends_on:
#       - mongodb
#       - server
#     environment:
#       - WATCHPACK_POLLING=true
# volumes:
#   mongo_data:
